"use client";
import { useEffect, useState } from "react";
type Player={name:string;position:string;team:string;fantasy:number;stats:string;logo?:string};
type Team={abbr:string;name:string;score:number;logo?:string};
type Game={id:string;status:string;clock?:string;period?:number;kickoff?:string;spread?:string;home:Team;away:Team;players:Player[]};
function fmt(n:number){return Number.isInteger(n)?String(n):n.toFixed(1)}
export default function Home(){
 const [games,setGames]=useState<Game[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[last,setLast]=useState<Date|null>(null);
 async function load(){try{setError("");const r=await fetch("/api/nfl",{cache:"no-store"});if(!r.ok)throw new Error("NFL feed unavailable");const d=await r.json();setGames(d.games||[]);setLast(new Date())}catch(e){setError(e instanceof Error?e.message:"Unable to load NFL data")}finally{setLoading(false)}}
 useEffect(()=>{load();const t=setInterval(load,15000);return()=>clearInterval(t)},[]);
 return <main><header className="top"><div><div className="eyebrow">LIVE NFL • FANTASY TRACKER</div><h1>NFL Live Center</h1><p>Every game, live score, and player PPR points in one place.</p></div><div className="live"><span className="dot"/> LIVE <button onClick={load}>Refresh</button></div></header>
 <section className="bar"><span>{games.length} games</span><span>Standard PPR</span><span>Updates every 15 seconds</span>{last&&<span>Updated {last.toLocaleTimeString()}</span>}</section>
 {error&&<div className="error">{error}</div>}
 {(() => { const leaderboard=games.flatMap(g=>g.players.map(p=>({...p,gameId:g.id}))).sort((a,b)=>b.fantasy-a.fantasy).slice(0,10); return leaderboard.length ? <section className="leaderboard card"><div className="sectionTitle"><div><span className="eyebrow">FANTASY LEADERBOARD</span><h2>Top PPR Performers</h2></div><span className="muted">Across today&apos;s games</span></div><div className="leaderRows">{leaderboard.map((p,i)=><div className="leaderRow" key={p.name+p.team+p.gameId}><span className="rank">{i+1}</span><b className="player-name">{p.logo&&<img src={p.logo} alt="" />}{p.name}</b><span className="leaderTeam">{p.team} • {p.position}</span><strong>{fmt(p.fantasy)}</strong></div>)}</div></section> : null; })()}
 {loading&&!games.length?<div className="empty">Loading NFL games…</div>:!games.length?<div className="empty">No games found for today.</div>:<div className="grid">{games.map(g=><GameCard key={g.id} game={g}/>)}</div>}
 <footer>Fantasy scoring: 1 pt/reception • 1 pt/10 rush/rec yards • 6 pt rush/rec TD • 1 pt/25 pass yards • 4 pt pass TD • −2 INT • −2 fumble lost • 2 pt conversions.</footer></main>
}
function GameCard({game:g}:{game:Game}){const live=/IN_PROGRESS|HALFTIME/i.test(g.status);return <article className="card"><div className="gamehead"><span className={live?"status liveText":"status"}>{g.status.replaceAll("_"," ")}</span><span>{g.clock&&g.period?g.clock+" • Q"+g.period:g.kickoff?"Kickoff "+g.kickoff+(g.spread?" • Spread "+g.spread:""):""}</span></div><div className="teams"><div><b className="team-name">{g.away.logo&&<img src={g.away.logo} alt="" />}{g.away.abbr}</b><span>{g.away.name}</span></div><strong>{g.away.score}</strong></div><div className="teams"><div><b className="team-name">{g.home.logo&&<img src={g.home.logo} alt="" />}{g.home.abbr}</b><span>{g.home.name}</span></div><strong>{g.home.score}</strong></div><div className="players"><div className="ptable"><span>PLAYER</span><span>POS</span><span>PPR</span></div>{g.players.map((p,i)=><div className="prow" key={p.name+p.team+i}><div><b className="player-name">{p.logo&&<img src={p.logo} alt="" />}{p.name}</b><small>{p.team} • {p.stats}</small></div><span>{p.position}</span><strong>{fmt(p.fantasy)}</strong></div>)}{!g.players.length&&<div className="noPlayers">Player stats appear when the feed provides box scores.</div>}</div></article>}
