"use client";
import { useEffect, useState } from "react";
type Player={name:string;position:string;team:string;fantasy:number;stats:string;logo?:string;statLine?:{passYds:number;passTD:number;interceptions:number;rushYds:number;rushTD:number;receptions:number;recYds:number;recTD:number;fumblesLost:number;twoPoint:number}};
type Team={abbr:string;name:string;score:number;logo?:string};
type Game={id:string;status:string;clock?:string;period?:number;kickoff?:string;spread?:string;overUnder?:string;moneyline?:{away:string|number;home:string|number};home:Team;away:Team;players:Player[]};
function fmt(n:number){return Number.isInteger(n)?String(n):n.toFixed(1)}
function elapsedMinutes(g:Game){if(!g.period||!g.clock)return 0;const m=g.clock.match(/^(\d+):([0-5]\d)$/);if(!m)return Math.min(g.period*15,60);const rem=Number(m[1])+Number(m[2])/60;return Math.max(0,Math.min(60,(g.period-1)*15+(15-rem)))}
function projection(g:Game,p:Player){const e=elapsedMinutes(g);return e>=10&&e<60&&p.fantasy>0?Math.max(p.fantasy,p.fantasy*(60/e)):0}
function detail(s?:Player["statLine"]){if(!s)return "";const parts:string[]=[];if(s.passYds)parts.push(s.passYds+" pass yds");if(s.passTD)parts.push(s.passTD+" pass TD");if(s.interceptions)parts.push(s.interceptions+" INT");if(s.rushYds)parts.push(s.rushYds+" rush yds");if(s.rushTD)parts.push(s.rushTD+" rush TD");if(s.receptions)parts.push(s.receptions+" rec");if(s.recYds)parts.push(s.recYds+" rec yds");if(s.recTD)parts.push(s.recTD+" rec TD");if(s.fumblesLost)parts.push(s.fumblesLost+" fumbles lost");return parts.join(" • ")}
export default function Home(){
 const [games,setGames]=useState<Game[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[last,setLast]=useState<Date|null>(null),[previous,setPrevious]=useState<Record<string,number>>({}),[pos,setPos]=useState("ALL");
 async function load(){try{setError("");const r=await fetch("/api/nfl",{cache:"no-store"});if(!r.ok)throw new Error("NFL feed unavailable");const d=await r.json();const next:Game[]=d.games||[];setPrevious(prev=>{const n:Record<string,number>={};next.flatMap(g=>g.players).forEach(p=>{const key=p.team+":"+p.name;if(prev[key]!==undefined)n[key]=prev[key];});return n});setGames(next);setLast(new Date())}catch(e){setError(e instanceof Error?e.message:"Unable to load NFL data")}finally{setLoading(false)}}
 useEffect(()=>{load();const t=setInterval(load,15000);return()=>clearInterval(t)},[]);
 const leaderboard=games.flatMap(g=>g.players.map(p=>({...p,gameId:g.id}))).filter(p=>pos==="ALL"||p.position===pos).sort((a,b)=>b.fantasy-a.fantasy).slice(0,10);
 const allPlayers=games.flatMap(g=>g.players.map(p=>({...p,game:g})));
 const movers=allPlayers.filter(p=>p.fantasy>0).sort((a,b)=>b.fantasy-a.fantasy).slice(0,5);
 const projected=allPlayers.filter(p=>p.fantasy>0&&projection(p.game,p)>0).sort((a,b)=>projection(b.game,b)-projection(a.game,a)).slice(0,5);
 return <main><header className="top"><div><div className="eyebrow">LIVE NFL • FANTASY TRACKER</div><h1>NFL Live Center</h1><p>Every game, live score, and player PPR points in one place.</p></div><div className="live"><span className="dot"/> LIVE <button onClick={load}>Refresh</button></div></header>
 <section className="bar"><span>{games.length} games</span><span>Standard PPR</span><span>Updates every 15 seconds</span>{last&&<span>Updated {last.toLocaleTimeString()}</span>}</section>
 {error&&<div className="error">{error}</div>}
 {leaderboard.length>0&&<section className="leaderboard card"><div className="sectionTitle"><div><span className="eyebrow">FANTASY LEADERBOARD</span><h2>Top PPR Performers</h2></div><span className="muted">Across today&apos;s games</span></div><div className="filters">{["ALL","QB","RB","WR","TE"].map(x=><button className={pos===x?"active":""} onClick={()=>setPos(x)} key={x}>{x}</button>)}</div><div className="leaderRows">{leaderboard.map((p,i)=><div className="leaderRow" key={p.name+p.team+p.gameId}><span className="rank">{i+1}</span><b className="player-name">{p.logo&&<img src={p.logo} alt=""/>}{p.name}</b><span className="leaderTeam">{p.team} • {p.position}</span><strong>{fmt(p.fantasy)}</strong></div>)}</div></section>}
 <section className="dashboardGrid"><section className="card movers"><div className="sectionTitle"><div><span className="eyebrow">FANTASY MOVERS</span><h2>Trending Now</h2></div></div>{movers.map(x=>{const old=previous[x.team+":"+x.name];const delta=old===undefined?0:x.fantasy-old;return <div className="moverRow" key={x.name+x.team}><b className="player-name">{x.logo&&<img src={x.logo} alt=""/>}{x.name}</b><span>{x.team}</span><strong>{delta>0?"+":""}{fmt(delta)}</strong></div>})}</section><section className="card movers"><div className="sectionTitle"><div><span className="eyebrow">LIVE PROJECTIONS</span><h2>Projected PPR Finish</h2></div></div>{projected.map(x=><div className="moverRow" key={x.name+x.team}><b className="player-name">{x.logo&&<img src={x.logo} alt=""/>}{x.name}</b><span>{fmt(x.fantasy)} now</span><strong>{fmt(projection(x.game,x))}</strong></div>)}</section></section>
 {loading&&!games.length?<div className="empty">Loading NFL games…</div>:!games.length?<div className="empty">No games found for today.</div>:<div className="grid">{games.map(g=><GameCard key={g.id} game={g}/>)}</div>}
 <footer>Fantasy scoring: 1 pt/reception • 1 pt/10 rush/rec yards • 6 pt rush/rec TD • 1 pt/25 pass yards • 4 pt pass TD • −2 INT • −2 fumble lost • 2 pt conversions.</footer></main>
}
function GameCard({game:g}:{game:Game}){const live=/IN_PROGRESS|HALFTIME/i.test(g.status);return <article className="card"><div className="gamehead"><span className={live?"status liveText":"status"}>{g.status.replaceAll("_"," ")}</span><span>{g.clock&&g.period?g.clock+" • Q"+g.period:g.kickoff?"Kickoff "+g.kickoff+(g.spread?" • Spread "+g.spread:"")+(g.overUnder?" • O/U "+g.overUnder:""):""}</span></div><div className="teams"><div><b className="team-name">{g.away.logo&&<img src={g.away.logo} alt=""/>}{g.away.abbr}</b><span>{g.away.name}</span></div><strong>{g.away.score}</strong></div><div className="teams"><div><b className="team-name">{g.home.logo&&<img src={g.home.logo} alt=""/>}{g.home.abbr}</b><span>{g.home.name}</span></div><strong>{g.home.score}</strong></div><div className="odds">{g.spread&&<span>Spread <b>{g.spread}</b></span>}{g.overUnder&&<span>O/U <b>{g.overUnder}</b></span>}{g.moneyline?.away!==""&&g.moneyline?.away!==undefined&&<span>{g.away.abbr} ML <b>{g.moneyline.away}</b></span>}{g.moneyline?.home!==""&&g.moneyline?.home!==undefined&&<span>{g.home.abbr} ML <b>{g.moneyline.home}</b></span>}</div><div className="players"><div className="ptable"><span>PLAYER / STATS</span><span>POS</span><span>PPR</span></div>{g.players.map((p,i)=><div className="prow" key={p.name+p.team+i}><div><b className="player-name">{p.logo&&<img src={p.logo} alt=""/>}{p.name}</b><small>{p.team} • {detail(p.statLine)||p.stats}</small>{projection(g,p)>0&&<em className="projection">Proj {fmt(projection(g,p))}</em>}</div><span>{p.position}</span><strong>{fmt(p.fantasy)}</strong></div>)}{!g.players.length&&<div className="noPlayers">Player stats appear when the feed provides box scores.</div>}</div></article>}
